version: '2'
services:
  mofuw:
    image: nimlang/nim:alpine
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, nimble server]
    networks:
      - mofuw
networks:
  mofuw:
    external: true

